restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishTypeListView,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    assign_driver,
    CookCreateView,
    CookYearsOfExperienceUpdateView,
    CookDeleteView,
    DishUpdateView,
    DishDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/assign-driver/", assign_driver, name="assign-cook"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookYearsOfExperienceUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">Previous</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item" style="background-color: #343a40; color: #007bff">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a>
      <img style="width: 50px; float: right; border-radius: 5px" src="/static/favicon/favicon.png" alt="restaurant-kitchen-service">
    </li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item" style="background-color: #343a40"><a href="{% url 'login'%}?next={{request.path}}">Login</a>
      <img style="width: 50px; float: right; border-radius: 5px" src="/static/favicon/favicon.png" alt="restaurant-kitchen-service">
    </li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'restaurant:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:cook-list' %}">All cooks</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dish-list' %}">All dishes</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dish-type-list' %}">All dish types</a></li>
</ul>