restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishTypeListView,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    assign_driver,
    CookCreateView,
    CookYearsOfExperienceUpdateView,
    CookDeleteView,
    DishUpdateView,
    DishDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/assign-driver/", assign_driver, name="assign-cook"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookYearsOfExperienceUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0, null=True)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self) -> str:
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    def __str__(self) -> str:
        return self.name

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MaxValueValidator

from restaurant.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "years_of_experience",
        )


class CookYearsOfExperienceUpdateForm(forms.ModelForm):
    years_of_experience = forms.CharField(
        validators=[
            MaxValueValidator(
                "50", message="Sorry, but you need to retire 😆"
            )
        ]
    )

    class Meta:
        model = Cook
        fields = ("years_of_experience",)


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username..."},
        )
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name..."},
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name..."},
        )
    )

restaurant/views.py
from http.client import HTTPResponse
from typing import Any

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import QuerySet
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from restaurant.forms import (
    CookCreationForm,
    CookYearsOfExperienceUpdateForm,
    DishForm, DishTypeSearchForm, DishSearchForm, CookSearchForm,
)
from restaurant.models import Cook, DishType, Dish


@login_required
def index(request) -> HTTPResponse:
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_visits": num_visits + 1,
    }

    return render(
        request, template_name="restaurant/index.html",
        context=context,
    )


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "restaurant/dish_type_list.html"
    context_object_name = "dish_type_list"
    queryset = DishType.objects.all()
    paginate_by = 5

    def get_context_data(
            self, *, object_list: Any = None, **kwargs: Any
    ) -> dict[str, Any]:
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={
                "name": name,
            }
        )

        return context

    def get_queryset(self) -> QuerySet[DishType]:
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    template_name = "restaurant/dish_type_form.html"
    context_object_name = "dish_type_list"
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    template_name = "restaurant/dish_type_form.html"
    context_object_name = "dish_type_list"
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "restaurant/dish_type_confirm_delete.html"
    context_object_name = "dish_type_list"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.select_related("dish_type")
    paginate_by = 5

    def get_context_data(
            self, *, object_list: Any = None, **kwargs: Any
    ) -> dict[str, Any]:
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={
                "name": name,
            }
        )

        return context

    def get_queryset(self) -> QuerySet[Dish]:
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = get_user_model().objects.all()

    def get_context_data(
            self, *, object_list: Any = None, **kwargs: Any
    ) -> dict[str, Any]:
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(
            initial={
                "username": username,
            }
        )

        return context

    def get_queryset(self) -> QuerySet[Cook]:
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("restaurant:cook-list")


class CookYearsOfExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookYearsOfExperienceUpdateForm
    success_url = reverse_lazy("restaurant:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cook-list")


@login_required
def assign_driver(
        request: WSGIRequest, pk: Any
) -> HttpResponsePermanentRedirect | HttpResponseRedirect:
    driver = Cook.objects.get(id=request.user.id)
    if Dish.objects.get(id=pk) in driver.cars.all():
        driver.cars.remove(pk)
    else:
        driver.cars.add(pk)
    return redirect("restaurant:dish-detail", pk=pk)

templates/restaurant/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:cook-list' %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    <a href="{% url 'restaurant:cook-update' pk=cook.id %}" class="btn btn-primary">Update years of experience</a>
    <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" class="btn btn-danger">Delete cook</a>
  </h1>
  <table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Years Of Experience</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>{{ cook.first_name }}</td>
      <td>{{ cook.last_name }}</td>
      <td>{{ cook.years_of_experience }}</td>
    </tr>
    </tbody>
  </table>

  <div>
    <h4 style="color: white">Dishes</h4>
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Dish Type</th>
      </tr>
      </thead>


      {% for dish in cook.dishes.all %}
        <tr>
          <td>{{ dish.id }}</td>
          <td>{{ dish.name }}</td>
          <td>{{ dish.dish_type.name }}</td>
        </tr>

      {% empty %}
        <p style="color: #007bff">No dishes!</p>
      {% endfor %}
    </table>
  </div>

{% endblock %}

templates/restaurant/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Cook List
    <a href="{% url 'restaurant:cook-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🔍" class="btn btn-primary">
  </form>
  {% if cook_list %}
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Years Of Experience</th>
      </tr>
      </thead>
      {% for cook in cook_list %}
        <tr>
          <td>{{ cook.id }}</td>
          <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
          <td>{{ cook.first_name }}</td>
          <td>{{ cook.last_name }}</td>
          <td>{{ cook.years_of_experience }}</td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no cooks in the service.</p>
  {% endif %}
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:dish-list' %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish details
    {{ dish.model }}
    <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
  <table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Dish Type</th>
      <th scope="col">Dish Description</th>
    </tr>
    </thead>
    <tbody>

    <tr>
      <td>{{ dish.dish_type.name }}</td>
      <td>{{ dish.description }}</td>
    </tr>

    </tbody>
  </table>
  <h1>
    Cooks
    {% if dish in user.dishes.all %}
      <a href="{% url 'restaurant:assign-cook' pk=dish.id %}" class="btn btn-danger" style="float: right">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'restaurant:assign-cook' pk=dish.id %}" class="btn btn-success" style="float: right">
        Assign me to this dish
      </a>
    {% endif %}
  </h1>

  <table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">Username</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
    </tr>
    </thead>
    <tbody>

    {% for cook in dish.cooks.all %}
      <tr>
        <td>{{ cook.username }}</td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
      </tr>
    {% endfor %}

    </tbody>
  </table>
{% endblock %}

templates/restaurant/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dish list
    <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🔍" class="btn btn-primary">
  </form>
  {% if dish_list %}
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price (UAH)</th>
        <th scope="col">Dish Type</th>
      </tr>
      </thead>
      <tbody>

      {% for dish in dish_list %}
        <tr>
          <td><a href="{% url 'restaurant:dish-detail' pk=dish.id %}">{{ dish.id }}</a></td>
          <td>{{ dish.name }}</td>
          <td>{{ dish.price }}</td>
          <td>{{ dish.dish_type.name }}</td>
        </tr>
      {% endfor %}

      </tbody>
    </table>
  {% else %}
    <p>There are no dishes in kitchen!</p>
  {% endif %}
{% endblock %}

templates/restaurant/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'restaurant:dish-type-list' %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

templates/restaurant/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Dish Type List
    <a href="{% url 'restaurant:dish-type-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% if dish_type_list %}
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>

      {% for type in dish_type_list %}
        <tr>
          <td>
            {{ type.id }}
          </td>
          <td>
            {{ type.name }}
          </td>
          <td>
            <a href="{% url 'restaurant:dish-type-update' pk=type.id %}">
              ✏️
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'restaurant:dish-type-delete' pk=type.id %}">
              ❌
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no dish types in the restaurant.</p>
  {% endif %}
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h1 style="background-color: #343a40">Restaurant Kitchen Home</h1>
    <p>Welcome to the Restaurant Kitchen Service!</p>
    <h3>Dynamic content</h3>
      <p><strong>Dishes - {{ num_dishes }}</strong></p>
      <p><strong>Cooks - {{ num_cooks }}</strong></p>
      <p><strong>Dish Types - {{ num_dish_types }}</strong></p>
    <p>You have visited this page
      <strong>{{ num_visits }}</strong> time{{ num_visits|pluralize }}
    </p>
    <hr>
  </div>

{% endblock %}